apiVersion: v1
kind: Namespace
metadata:
  name: zerodha-staging
  labels:
    name: zerodha-staging
    environment: staging
    app.kubernetes.io/name: tradeflow-zerodha
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: tradeflow
    app.kubernetes.io/managed-by: kubectl