#pragma once

#include "order_management_system.hpp"
#include "trading_allocator.hpp"
#include "latency_tracker.hpp"
#include <atomic>
#include <array>
#include <functional>

namespace tradeflow {

/**
 * Strategy signal types
 */
enum class SignalType : uint8_t {
    NONE = 0,
    BUY = 1,
    SELL = 2,
    CLOSE_LONG = 3,
    CLOSE_SHORT = 4,
    STOP_LOSS = 5,
    TAKE_PROFIT = 6
};

/**
 * Strategy signal strength
 */
enum class SignalStrength : uint8_t {
    WEAK = 1,
    MEDIUM = 2,
    STRONG = 3,
    VERY_STRONG = 4
};

/**
 * Trading signal generated by strategy
 */
struct TradingSignal {
    uint64_t strategy_id;
    uint64_t timestamp_nanos;
    char symbol[16];
    SignalType signal_type;
    SignalStrength strength;
    uint64_t target_price;
    uint32_t suggested_quantity;
    uint64_t stop_loss_price;
    uint64_t take_profit_price;
    double confidence_score;  // 0.0 to 1.0
};

/**
 * Position information for strategy
 */
struct StrategyPosition {
    char symbol[16];
    int64_t quantity;  // Positive for long, negative for short
    uint64_t avg_entry_price;
    uint64_t current_price;
    int64_t unrealized_pnl;
    int64_t realized_pnl;
    uint64_t last_update_time;
};

/**
 * Strategy execution statistics
 */
struct StrategyStats {
    uint64_t signals_generated;
    uint64_t orders_placed;
    uint64_t orders_filled;
    uint64_t profitable_trades;
    uint64_t losing_trades;
    int64_t total_pnl;
    double win_rate;
    double sharpe_ratio;
    uint64_t max_drawdown;
};

/**
 * Risk control parameters for strategy execution
 */
struct StrategyRiskControls {
    uint64_t max_position_size;
    uint64_t max_daily_loss;
    uint64_t max_drawdown;
    double max_portfolio_allocation;  // 0.0 to 1.0
    uint32_t max_orders_per_second;
    bool enable_stop_loss;
    bool enable_take_profit;
    double stop_loss_percentage;      // 0.0 to 1.0
    double take_profit_percentage;    // 0.0 to 1.0
};

/**
 * Strategy execution callback interface
 */
class StrategyCallback {
public:
    virtual ~StrategyCallback() = default;
    
    /**
     * Called when a trading signal is generated
     */
    virtual void on_signal_generated(const TradingSignal& signal) = 0;
    
    /**
     * Called when an order is placed
     */
    virtual void on_order_placed(uint64_t order_id, const TradingSignal& signal) = 0;
    
    /**
     * Called when an order is filled
     */
    virtual void on_order_filled(uint64_t order_id, uint32_t filled_quantity, uint64_t fill_price) = 0;
    
    /**
     * Called when position is updated
     */
    virtual void on_position_updated(const StrategyPosition& position) = 0;
    
    /**
     * Called when risk limits are breached
     */
    virtual void on_risk_breach(const char* reason) = 0;
};

/**
 * Ultra-low latency strategy execution engine
 * Processes trading signals and manages automated trade execution
 */
class StrategyExecutionEngine {
public:
    static constexpr size_t MAX_STRATEGIES = 1000;
    static constexpr size_t MAX_POSITIONS = 10000;
    static constexpr size_t MAX_SIGNALS_PER_SECOND = 100000;
    
    StrategyExecutionEngine(OrderManagementSystem& oms, TradingAllocator& allocator, 
                           LatencyTracker& latency_tracker);
    ~StrategyExecutionEngine() = default;
    
    // Non-copyable, non-movable
    StrategyExecutionEngine(const StrategyExecutionEngine&) = delete;
    StrategyExecutionEngine& operator=(const StrategyExecutionEngine&) = delete;
    StrategyExecutionEngine(StrategyExecutionEngine&&) = delete;
    StrategyExecutionEngine& operator=(StrategyExecutionEngine&&) = delete;
    
    /**
     * Register a strategy for execution
     * @param strategy_id Unique strategy identifier
     * @param user_id User who owns the strategy
     * @param risk_controls Risk parameters for the strategy
     * @param callback Callback interface for strategy events
     * @return true if strategy registered successfully
     */
    bool register_strategy(uint64_t strategy_id, uint32_t user_id, 
                          const StrategyRiskControls& risk_controls,
                          StrategyCallback* callback) noexcept;
    
    /**
     * Unregister a strategy
     * @param strategy_id Strategy to unregister
     * @return true if strategy was unregistered
     */
    bool unregister_strategy(uint64_t strategy_id) noexcept;
    
    /**
     * Process trading signal (ultra-low latency)
     * @param signal Trading signal to process
     * @return true if signal was processed successfully
     */
    bool process_signal(const TradingSignal& signal) noexcept;
    
    /**
     * Update market price for position tracking
     * @param symbol Trading symbol
     * @param price Current market price
     */
    void update_market_price(const char* symbol, uint64_t price) noexcept;
    
    /**
     * Get current position for strategy and symbol
     * @param strategy_id Strategy identifier
     * @param symbol Trading symbol
     * @return Pointer to position if found, nullptr otherwise
     */
    const StrategyPosition* get_position(uint64_t strategy_id, const char* symbol) const noexcept;
    
    /**
     * Get strategy statistics
     * @param strategy_id Strategy identifier
     * @return Strategy statistics
     */
    StrategyStats get_strategy_stats(uint64_t strategy_id) const noexcept;
    
    /**
     * Enable/disable strategy execution
     * @param strategy_id Strategy identifier
     * @param enabled True to enable, false to disable
     */
    void set_strategy_enabled(uint64_t strategy_id, bool enabled) noexcept;
    
    /**
     * Emergency stop all strategies
     */
    void emergency_stop_all() noexcept;
    
    /**
     * Get engine performance statistics
     */
    struct EngineStats {
        uint64_t signals_processed;
        uint64_t orders_generated;
        uint64_t risk_violations;
        LatencyTracker::LatencyStats signal_processing_latency;
        LatencyTracker::LatencyStats order_execution_latency;
    };
    
    EngineStats get_engine_stats() const noexcept;
    
    /**
     * Reset all statistics
     */
    void reset_stats() noexcept;
    
private:
    OrderManagementSystem& oms_;
    TradingAllocator& allocator_;
    LatencyTracker& latency_tracker_;
    
    // Strategy management
    struct StrategyInfo {
        uint64_t strategy_id;
        uint32_t user_id;
        StrategyRiskControls risk_controls;
        StrategyCallback* callback;
        StrategyStats stats;
        std::atomic<bool> enabled;
        std::atomic<uint64_t> last_signal_time;
        std::atomic<uint32_t> signals_this_second;
        bool active;
    };
    
    alignas(64) std::array<StrategyInfo, MAX_STRATEGIES> strategies_;
    std::atomic<size_t> strategy_count_{0};
    
    // Position tracking
    struct PositionKey {
        uint64_t strategy_id;
        char symbol[16];
        
        bool operator==(const PositionKey& other) const noexcept {
            return strategy_id == other.strategy_id && 
                   std::strcmp(symbol, other.symbol) == 0;
        }
    };
    
    struct PositionInfo {
        PositionKey key;
        StrategyPosition position;
        std::atomic<bool> active;
    };
    
    alignas(64) std::array<PositionInfo, MAX_POSITIONS> positions_;
    std::atomic<size_t> position_count_{0};
    
    // Performance tracking
    std::atomic<uint64_t> signals_processed_{0};
    std::atomic<uint64_t> orders_generated_{0};
    std::atomic<uint64_t> risk_violations_{0};
    
    LatencyTracker signal_processing_latency_;
    LatencyTracker order_execution_latency_;
    
    // Emergency stop flag
    std::atomic<bool> emergency_stop_{false};
    
    // Helper methods
    size_t find_strategy_index(uint64_t strategy_id) const noexcept;
    size_t find_position_index(uint64_t strategy_id, const char* symbol) const noexcept;
    size_t create_position(uint64_t strategy_id, const char* symbol) noexcept;
    
    bool validate_signal(const TradingSignal& signal, const StrategyInfo& strategy) noexcept;
    bool check_risk_limits(const TradingSignal& signal, const StrategyInfo& strategy) noexcept;
    
    uint32_t calculate_position_size(const TradingSignal& signal, const StrategyInfo& strategy) noexcept;
    uint64_t calculate_stop_loss_price(const TradingSignal& signal, const StrategyInfo& strategy) noexcept;
    uint64_t calculate_take_profit_price(const TradingSignal& signal, const StrategyInfo& strategy) noexcept;
    
    void update_position(uint64_t strategy_id, const char* symbol, 
                        int64_t quantity_change, uint64_t price) noexcept;
    void update_strategy_stats(uint64_t strategy_id, bool profitable_trade, int64_t pnl) noexcept;
    
    OrderExecutionResult execute_signal(const TradingSignal& signal, const StrategyInfo& strategy) noexcept;
};

} // namespace tradeflow